import * as path from 'path';
import * as fs from 'fs';

/**
 * 生成某个目录的index.ts，导出所有exports
 * @param dir 基于src的相对路径
 * @param root 根路径
 */
export function generateIndex(dir: string, root: string = process.cwd()) {
  const cwd = path.join(root, dir);
  if (!fs.existsSync(cwd)) {
    return;
  }
  const list = fs.readdirSync(cwd, { withFileTypes: true });
  // tslint:disable-next-line:variable-name
  let index_ts = `// generated by scripts/generate-index at ${new Date()}\n\n`;
  for (const info of list) {
    if (info.isFile()) {
      if (
        info.name === 'index.ts' ||
        !/\.ts$/.test(info.name) ||
        /\.(d|spec)\.ts$/.test(info.name)
      ) {
        continue;
      }

      const file = fs.readFileSync(path.join(cwd, info.name), {
        encoding: 'utf-8',
      });
      if (!/^export[ =]/m.test(file)) {
        // no exports
        continue;
      }
      index_ts += `export * from './${path.basename(
        info.name,
        path.extname(info.name),
      )}';\n`;
    }
  }
  fs.writeFileSync(path.join(cwd, 'index.ts'), index_ts);
}
